### ISSUE TITLE
Expose refreshAuth

### ISSUE THREAD

**Issue by kuroljov** [hasura/react-check-auth#8]
Hi,

Can we expose `refreshAuth` somehow?

Sometimes you just need some sort of `signOut` function that will handle 

- removing token from localstorage
- `...`
- and lastly we need to update check auth cycle to show sign In form again

Can/Will you do it? Or can you just give me a hint? Or you think it's a bad idea?

**Comment by karthikvt26** [comment]
Hey you will get `refreshAuth` also in the object. You can access it as below.

```
    <AuthConsumer>
        { ({ userInfo, refreshAuth }) => {
            return (
                ... your code
            );
        }}
    </AuthConsumer>
```

**Comment by karthikvt26** [comment]
Hmmm interesting. Currently all the auth information is locked inside the state of the `AuthProvider` component instance and ``refreshAuth`` is an instance method which just calls the fetch function and updates the above state.

Please correct me if I am wrong. You would like to have ``refreshAuth`` as an exported function so that you can call ``refreshAuth`` from one of the link (apollo-link-error) configured with the operation? 

The only way to solve this problem is to have the state outside the component. For example in a store like redux and updating the store using Action dispatchers. 

Your thoughts?

**Comment by cvinson** [comment]
@kuroljov I seem to be running into all the same issues as you.  Here's how I addressed this one:
Have your handler function take in `refreshAuth` return a function, like this:

`
const handleClick = (refreshAuth) => (any, args, needed) => {
  doSomethingLikeRemoveToken();
  doSomethingElse();
  refreshAuth();
}

<AuthConsumer>
  {({ refreshAuth }) => (
    <button onClick={handleClick(refreshAuth)}>Click Here</button>
  )}
</AuthConsumer>
`
That way the function returned by `handleClick(refreshAuth)` has `refreshAuth` in scope.

**Comment by kuroljov** [comment]
@cvinson it seems like a hacky way to do what I need which is expose refreshAuth.

I don't know guys what exactly it requires to solve this but it would be really nice. Maybe we can define refreshAuth somewhere and bind it to component later? It that way we could solve this issue?

**Comment by kuroljov** [comment]
Will close for now but maybe will come up with PR in the future
